### ISSUE TITLE
How might this also work with WIN7/10 etc...

### ISSUE THREAD

**Issue by themindfactory** [wolfgangB33r/blogPostMaterial#1]
So this works for Android, can it be made to work with WIN7/10 and IOS?

Thanks!

**Comment by wolfgangB33r** [comment]
@themindfactory what exactly do you mean? this repo contains different examples each for individual blog posts.

**Comment by themindfactory** [comment]
The code is targetted at Android, I was asking how does it differ from IOS?

**Comment by wolfgangB33r** [comment]
The code in this repository is mostly Python and can be run on any machine with Python on.
